# permissions for end users to view workflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-viewer-role
rules:
- apiGroups:
  - kie.kogito.sw.org
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kie.kogito.sw.org
  resources:
  - workflows/status
  verbs:
  - get
