name: "Bump Version"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
      new_version:
        description: "New version"
        required: true

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set release version
        shell: bash
        run: ./bump_version.sh ${{ github.event.inputs.release_version }}

      - name: Commit new release files
        run: |
          git config --local user.email "kietooling@gmail.com"
          git config --local user.name "Kogito Tooling Bot"
          git commit -m "Release ${{ github.event.inputs.release_version }}" -a
        
      - name: Push release branch
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.KOGITO_TOOLING_BOT_TOKEN }}
          branch: '${{ github.event.inputs.release_version }}-release'

      - name: Bump version
        shell: bash
        run: ./bump_version.sh ${{ github.event.inputs.new_version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.KOGITO_TOOLING_BOT_TOKEN }}
          commit-message: Bump version to ${{ github.event.inputs.new_version }}
          committer: Kogito Tooling Bot <kietooling@gmail.com>
          branch: bump-version-to-${{ github.event.inputs.new_version }}
          delete-branch: true
          title: Bump version to ${{ github.event.inputs.new_version }}
