name: "CI :: Daily cleanup (kogito-online-ci)"

on:
  schedule:
    - cron: "0 1 * * *" # 1am UTC everyday
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'kiegroup/kie-tools'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: "Clone kogito-online-ci"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.KIE_TOOLS_BOT_TOKEN }}
          path: kogito-online-ci
          repository: kiegroup/kogito-online-ci
          ref: gh-pages
          fetch-depth: 0

      - name: "Remove builds older than 14 days"
        id: remove_build_artifacts
        run: |
          git config --global user.email "kietoolsbot@gmail.com"
          git config --global user.name "KIE Tools Bot (kiegroup)"
          cd kogito-online-ci
          limitDate=$(date -d "-14 days" +%s)
          echo "limitDate: $limitDate"
          for buildDir in */*/;
          do
            buildDate=$(git log -1 --pretty="format:%ct" --date="iso-strict" -- $buildDir)
            echo "$buildDir buildDate: $buildDate"
            if [ $buildDate -lt $limitDate ]; then
              echo "Should remove: $buildDir"
              rm -rf $buildDir
              git add . && git commit -m "KIE Tools Daily Cleanup - removing build $buildDir" || echo "No changes."
            else
              echo "Should NOT remove: $buildDir"
            fi
          done
          git push origin gh-pages
          cd -
        shell: bash
