name: "CI :: Build (full)"

on:
  push:
    branches: [main]
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.event.pull_request && format('ci-build-full-pr-{0}', github.event.pull_request.number) || format('ci-build-full-push-main-{0}', github.sha) }}
  cancel-in-progress: true

jobs:
  run:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Support longpaths"
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: "Setup kie-tools-bot"
        uses: ./.github/actions/setup-kie-tools-bot

      - name: "Merge PR changes"
        id: merge_pr_changes
        uses: ./.github/actions/merge-pr-changes

      - name: "Setup CI patterns"
        id: ci_patterns
        uses: ./.github/actions/setup-ci-patterns

      - name: "Check if should run or not"
        id: check_diff_paths
        shell: bash
        run: |
          export NON_SOURCE_FILES_PATTERNS=(${{ steps.ci_patterns.outputs.non_source_files_patterns }})
          echo "Non-source files patterns:"
          echo ${#NON_SOURCE_FILES_PATTERNS[@]}
          printf '%s\n' "${NON_SOURCE_FILES_PATTERNS[@]}"

          export NON_SOURCE_FILES_PATTERNS_FOR_GIT_DIFF=$(printf '%s\n' ${NON_SOURCE_FILES_PATTERNS[@]} | xargs -n 1 -I{} echo -n "'"':!'"{}""' ")
          echo "Non-source files patterns for git diff:"
          echo ${#NON_SOURCE_FILES_PATTERNS_FOR_GIT_DIFF[@]}
          echo $NON_SOURCE_FILES_PATTERNS_FOR_GIT_DIFF

          export CHANGED_SOURCE_PATHS=($(eval "git diff --name-only ${{ steps.merge_pr_changes.outputs.base_sha }} ${{ steps.merge_pr_changes.outputs.head_sha }} -- $NON_SOURCE_FILES_PATTERNS_FOR_GIT_DIFF"))
          echo "Changed source paths:"
          echo ${#CHANGED_SOURCE_PATHS[@]}
          printf '%s\n' "${CHANGED_SOURCE_PATHS[@]}"

          export CHANGED_SOURCE_PATHS_IN_ROOT=($(printf '%s\n' "${CHANGED_SOURCE_PATHS[@]}" | grep -v -e "^packages" -e "^examples"))
          echo "Changed source paths in root:"
          echo ${#CHANGED_SOURCE_PATHS_IN_ROOT[@]}
          printf '%s\n' "${CHANGED_SOURCE_PATHS_IN_ROOT[@]}"

          if [ ${#CHANGED_SOURCE_PATHS[@]} -eq 0 ]; then
            echo 'No source files changed; `CI :: Build (full)` will not run.'
            echo "::set-output name=should_run::false"
          elif [ ! ${{ github.event.pull_request }} ]; then
            echo 'Push to the `main` branch happened; `CI :: Build (full)` will run.'
            echo "::set-output name=should_run::true"
          elif [ ${#CHANGED_SOURCE_PATHS_IN_ROOT[@]} -eq 0 ]; then
            echo 'No source files changed in root; `CI :: Build (full)` will not run.'
            echo "::set-output name=should_run::false"
          else
            echo 'Source files changed in root; `CI :: Build (full)` will run.'
            echo "::set-output name=should_run::true"
          fi

          echo "Done"

      - name: "Start telemetry service"
        if: steps.check_diff_paths.outputs.should_run == 'true'
        uses: runforesight/workflow-telemetry-action@7771f879afebe55ef1009a49f0b8a5d9089d8bc7

      - name: "Setup environment"
        if: steps.check_diff_paths.outputs.should_run == 'true'
        uses: ./.github/actions/setup-env

      - name: "Bootstrap"
        if: steps.check_diff_paths.outputs.should_run == 'true'
        uses: ./.github/actions/bootstrap

      - name: "Build"
        if: steps.check_diff_paths.outputs.should_run == 'true'
        env:
          WEBPACK__minimize: "false"
          WEBPACK__tsLoaderTranspileOnly: "false"
          KIE_TOOLS_BUILD__runLinters: "true"
          KIE_TOOLS_BUILD__runTests: "true"
          KIE_TOOLS_BUILD__runIntegrationTests: ${{ runner.os == 'Linux' }}
          KIE_TOOLS_BUILD__buildContainerImages: "true"
          KIE_TOOLS_BUILD__buildExamples: "true"
          KIE_TOOLS_BUILD__ignoreTestFailures: ${{ !github.event.pull_request }}
          KIE_TOOLS_BUILD__ignoreIntegrationTestFailures: ${{ !github.event.pull_request }}
          DISPLAY: ":99.0"
          START_SERVER_AND_TEST_INSECURE: "true"
        run: |
          pnpm -r build:prod

      - name: "Check tests result (`main` only)"
        if: always() && !cancelled() && steps.check_diff_paths.outputs.should_run == 'true' && !github.event.pull_request
        uses: mikepenz/action-junit-report@1b47bb811362f3d8d753fc148cb7a13ec9e55570
        with:
          check_name: "-"
          annotate_only: true
          fail_on_failure: true
          report_paths: |
            ${{ steps.ci_patterns.outputs.tests_reports_patterns }}
            ${{ steps.ci_patterns.outputs.integration_tests_reports_patterns }}

      - name: "Check hanging uncommitted files (you should commit those!)"
        if: always() && !cancelled() && steps.check_diff_paths.outputs.should_run == 'true'
        shell: bash
        run: |
          git diff
          [ "0" == "$(git diff | wc -l | tr -d ' ')" ]

      - name: "Upload reports and artifacts"
        if: always() && !cancelled() && steps.check_diff_paths.outputs.should_run == 'true'
        uses: ./.github/actions/upload-ci-reports-and-artifacts

      - name: "Print storage usage (after build)"
        shell: bash
        run: |
          du -sh .
