name: "Maven :: Publish Backend Quarkus Runner unpacked"

on:
  workflow_dispatch:
    inputs:
      mvnVersion:
        description: 'Maven version'
        required: true
      npmVersion:
        description: 'NPM version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          cd .github/supporting-files/maven-artifacts/quarkus-runner-unpacked
          mvn package -B -Dversion.quarkus.runner=${{ github.event.inputs.mvnVersion }}
          npm version ${{ github.event.inputs.npmVersion }}
          echo "//registry.npmjs.org/:_authToken=${{ secrets.KIEGROUP_NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public