name: "Release :: Dry Run"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # 4am UTC everyday
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/release*"
      - ".github/actions/**"

concurrency:
  group: ${{ github.event.pull_request && format('release-dry-run-pr-{0}', github.event.pull_request.number) || format('release-dry-run-ref-{0}', github.ref_name) }}
  cancel-in-progress: true

jobs:
  dry_run:
    uses: ./.github/workflows/release_build.yml
    with:
      dry_run: true
      base_ref: ${{ github.event.pull_request && github.base_ref || github.ref }}
      runners: '{"dmn_dev_sandbox_image":"true","kie_sandbox_image":"true","kie_sandbox_extended_services_image":"true","git_cors_proxy_image":"true","online_editor":"true","chrome_extensions":"true","vscode_extensions_dev":"true","vscode_extensions_prod":"true","desktop":"true","npm_packages":"true","standalone_editors_cdn":"true","extended_services":"true","dashbuilder":"true","dashbuilder_images":"true","serverless_logic_sandbox":"true","serverless_logic_sandbox_base_image":"true","openjdk11_mvn_image":"true","kn_plugin_workflow":"true"}'
