name: Run S2I modules Bats Tests

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils --fix-missing
      - name: install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh $HOME

      - name: run kogito-data-index tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-data-index/tests/bats

      - name: run kogito-trusty tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-trusty/tests/bats

      - name: run kogito-explainability tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-explainability/tests/bats

      - name: run kogito-graalvm-scripts tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-graalvm-scripts/tests/bats

      - name: run kogito-jobs-service tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-jobs-service/tests/bats

      - name: run kogito-kubernetes-client tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-kubernetes-client/tests/bats/

      - name: run kogito-management-console tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-management-console/tests/bats/

      - name: run kogito-maven tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-maven/tests/bats

      - name: run kogito-persistence tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-persistence/tests/bats

      - name: run kogito-s2i-core tests
        working-directory: ${{ github.workspace }}
        run: |
          $HOME/bin/bats modules/kogito-s2i-core/tests/bats

