name: "Sonar :: stunner-editors"
on:
  push:
    branches:
      - main
    paths:
      - "packages/stunner-editors/**"

jobs:
  build:
    name: Build for Sonar
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: "Merge Changes"
        if: ${{ github.event.pull_request }}
        shell: bash
        run: |
          user=$(node -e "console.log('${{ github.event.pull_request.head.label }}'.match(/(.+)\:(.+)$/)[1])")
          git remote add $user https://github.com/$user/kogito-tooling.git
          git fetch $user
          git merge --squash $user/${{ github.head_ref }}

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          os: ${{ runner.os }}

      - name: "Cache SonarCloud packages"
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-stunner-editors
          restore-keys: ${{ runner.os }}-sonar-stunner-editors

      - name: "Build with Maven to measure code coverage"
        run: |
          lerna run build:dev:until @kogito-tooling/stunner-editors
          cd packages/stunner-editors
          mvn clean install --fail-at-end -Prun-code-coverage -pl '!kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime,!kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing,!lienzo-webapp'

      - name: "Analyze with Sonar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd packages/stunner-editors
          mvn -B validate org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=org.kie.kogito:kogito-tooling -Dsonar.organization=kiegroup -Dsonar.host.url=https://sonarcloud.io -DskipTests -Dgwt.compiler.skip -Dsonar.login=${{ env.SONARCLOUD_TOKEN }} -pl '!kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime,!kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing,!lienzo-webapp'
